# Travis configuration
language: python
python:
  - "2.7"

# environment variables
env:
  - TIGERGRADER_SETTINGS=debug/configuration.py

# install dependencies
install:
  - "sudo apt-get install dwdiff"
  - "pip install nose nosexcover mock python-coveralls"
  - "pip install ."


# run tests
script:
  - "nosetests --with-xcoverage --cover-package=tigergrader --cover-tests tigergrader/tests/"
  
after_success:
  - coveralls
